"use client";
import { useState } from "react";
import type { GitCommitAction } from "@/lib/api/workflow-types";
import { buildPublicationRequest, publicationVisibleForCommit } from "@/lib/github-publication";
type Publication = { id: string; approval_request_id: string; repository_identity: { owner?: string; repository?: string }; base_branch: string; prepared_remote_base_sha: string; local_commit_sha: string; branch_ref: string; pr_title: string; pr_body_hash: string; publication_fingerprint: string; policy_effect: string; status: string; failure_code?: string | null; remote_commit_sha?: string | null; pr_number?: number | null; pr_url?: string | null; pr_body: string };
export function GitHubPublication({ action }: Readonly<{ action: GitCommitAction }>) {
  const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [publication, setPublication] = useState<Publication | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  void error;
  if (!publicationVisibleForCommit(action.status)) return null;
  async function prepare() { setBusy(true); setError(null); try { const response = await fetch(`/api/git-commit-actions/${action.id}/github-publications`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(buildPublicationRequest(title, body)) }); const value = await response.json() as Publication & { message?: string }; if (!response.ok) throw new Error(value.message || "Publication preparation failed."); setPublication(value); } catch (cause) { setError(cause instanceof Error ? cause.message : "Publication preparation failed."); } finally { setBusy(false); } }
  async function decide(decision: "approve" | "reject") { if (!publication) return; setBusy(true); try { const response = await fetch(`/api/approvals/${publication.approval_request_id}/${decision}`, { method: "POST" }); const value = await response.json() as Publication & { message?: string }; if (!response.ok) throw new Error(value.message || "Approval decision failed."); setPublication(value); } catch (cause) { setError(cause instanceof Error ? cause.message : "Approval decision failed."); } finally { setBusy(false); } }
  return <section className="challenge-panel" aria-label="GitHub publication"><div><p className="eyebrow">GitHub publication</p><h4>Publish the exact local commit</h4><p>Repository, base, branch, commit, policy, and actor authority are server-owned.</p></div>{!publication ? <><label>PR title<input required maxLength={160} value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>PR body<textarea maxLength={16384} value={body} onChange={(event) => setBody(event.target.value)} /></label><button className="primary-button" disabled={busy || title.length < 1} onClick={() => void prepare()}>Prepare publication</button></> : <><dl className="model-metadata"><div><dt>Repository</dt><dd>{publication.repository_identity.owner}/{publication.repository_identity.repository}</dd></div><div><dt>Base</dt><dd>{publication.base_branch} · {publication.prepared_remote_base_sha}</dd></div><div><dt>Local commit</dt><dd>{publication.local_commit_sha}</dd></div><div><dt>Branch</dt><dd>{publication.branch_ref}</dd></div><div><dt>PR title</dt><dd>{publication.pr_title}</dd></div><div><dt>Policy / status</dt><dd>{publication.policy_effect} · {publication.status}</dd></div><div><dt>Fingerprint</dt><dd>{publication.publication_fingerprint}</dd></div>{publication.remote_commit_sha ? <div><dt>Remote commit</dt><dd>{publication.remote_commit_sha}</dd></div> : null}{publication.pr_number ? <div><dt>PR</dt><dd>{publication.pr_url ? <a href={publication.pr_url} rel="noreferrer">#{publication.pr_number}</a> : `#${publication.pr_number}`}</dd></div> : null}</dl><pre>{publication.pr_body}</pre>{publication.failure_code ? <p className="inline-error">Failure: {publication.failure_code}</p> : null}{publication.status === "PENDING_APPROVAL" ? <div className="challenge-actions"><button className="primary-button" disabled={busy} onClick={() => void decide("approve")}>Approve publication</button><button className="danger-button" disabled={busy} onClick={() => void decide("reject")}>Reject</button></div> : null}</>}</section>;
}
